### ISSUE TITLE
Google Chrome flagged as dangerous

### ISSUE THREAD

**Issue by badjano** [vertopal/vertopal-cli#1]
### Describe the bug

Google Chrome flagged as dangerous

### Steps (or code) to reproduce

Google Chrome flagged as dangerous

### Expected behaviour

Google Chrome flagged as dangerous

### Operating System

Windows

### Version of Vertopal CLI

1.1

### Installation source

Static binary from GitHub release page

**Comment by vertonim** [comment]
We are using PyInstaller version 5.7.0 to create Vertopal CLI binaries. All the building steps and tasks are automated using GitHub Workflows. The source code, build process, and logs are made public for maximum clarity.

The result of the security vendors' analysis for Vertopal CLI 1.0.0 (Windows), is available at:
https://www.virustotal.com/gui/file/5168fed75893cb61ec48aaac0bc77b72cbd0caf474dae25fdeb64407591d84dd?nocache=1

This analysis confirms that the binary file is safe. If you are still receiving malicious alerts, it is a false positive, related to PyInstaller. 

You can find more information at the following links:
https://discuss.python.org/t/pyinstaller-false-positive/43171
https://plainenglish.io/blog/pyinstaller-exe-false-positive-trojan-virus-resolved-b33842bd3184
